### ISSUE TITLE
  Class 'TechTailor\RPG\RPGServiceProvider' not found  

### ISSUE THREAD

**Issue by rizwanzoofy** [TechTailor/RPG#6]
On command, **composer install**, there is error on screen   **Class 'TechTailor\RPG\RPGServiceProvider' not found**

**Comment by TechTailor** [comment]
If you are running Laravel 5.5 or higher version, you don't need to follow [Step-2](https://github.com/TechTailor/RPG#step-2-add-the-service-provider-skip-this-step-for-laravel-55-or-higher) and [Step-3](https://github.com/TechTailor/RPG#step-3-add-the-alias-skip-this-step-for-laravel-55-or-higher). Just do `composer require techtailor/rpg` and the package should work.

Did you add `TechTailor\RPG\RPGServiceProvider::class,` to your config/app.php file before requiring the package itself?

-TT

**Comment by rizwanzoofy** [comment]
Thanks for the help.
